### PR TITLE
Change data structure to .csv + .toml

### PR DESCRIPTION
**Pull request by kdund**
Aims to meet #11 -- 

- store limits etc. in .csv files
- have the names of these files in a consistent format - SIGNATURE(_MODIFIER)_EXPERIMENT_YEAR_ARXIVNUMBER.csv [so e.g. WIMPSI_XENONNT_2023_2303.14729.csv
- then use this same name as the key in a .yaml file where we store things we want to know about this .csv file, that is all the fields we previously had in a per-result .json
    this also includes which .csv column is wimp_mass, upper_limit, sensitivity etc.
    
You can also put a .csv in the data folder and open it-- you just won't have metadata to help you set columns etc. (though you can set this in the initialisation): 

image

### CODE REVIEW

**Comment by ibles** [comment]
I really like these changes, Knut! What is the metadata stored in the toml file used for? Is it only for reference or can we use this information when accessing the corresponding csv files? If the latter, it would be good to add an example in the snippet of code you posted for how to access data from the toml file.

**Comment by kdund** [comment]
Hi, @ibles ! at the moment, I was thinking of just having the plotter return also a reference list, but all of these properties are accessible as e.g. `DDresult.referece` -- so you could for example then order all results by year, or add it to the legend programatically. Other properties such as independent_variable_unit might be used either for a sanity check or to automatically convert units if we want to be fancy (using https://pypi.org/project/numericalunits/?) And lastly provenance is more to help remember the history of a certain line

@yuema137 was busy this week, but we had a small chat, and I think we can also use a lot from that for the plotting, and the idea of partial search/mathcing was directly stolen from her, only using glob to do it :)

**Comment by kdund** [comment]
It is also a general feature/benefit of this approach that if you just need sth quick you can just add a .csv, no need to add to the .toml to start with. 
(any way to add multiple search paths, I wonder?)

**Comment by kdund** [comment]
I think it can be merged in this state, but we should: 
1) Rename all the .csvs included in the SIGNATURE_(POSTFIX)_EXPERIMENT_ARXIV.csv pattern
2) add .bibtex at least to all the ones we have. 
afterwards

**Comment by ibles** [comment]
That sounds like a great idea. I like having the metadata assigned to each csv file for easier data manipulation, while at the same time not being too presciptive about this so analyzers can play with a new csv file easily. I am also quite busy this week, but I can help with adding metadata for the existing files in the repository. No need to wait though, if you are happy with these changes, feel free to go ahead with these merge requests and I will create a new merge request.

**Comment by kdund** [comment]
Lets merge early next week, then!

**Review by ibles — APPROVED** [review]
Ready to go! The changes look good to me. I added the metadata for PandaX's 2022 upper limit and I made some improvements to the Example plot notebook. The plot in that notebook currently looks like the one below. You can proceed with the merge request as far as I am concerned.

image

**Pull request merged**
