### PR TITLE
set outline width to two units makes for pretty plots

### PR DESCRIPTION
**Pull request by kdund**
I found some nice options from labellines that makes the text outline a thin white (or background color in general) line which makes the labels very prettily readable: 
image

### CODE REVIEW

**Comment by deisting** [comment]
Testing on an empty Python 3.11.7
- I may just be stupid, but shoudn't `pip install .` also install everything in the requirements.txt ?
- `from importlib_resources import files` -> `ModuleNotFoundError: No module named 'importlib_resources'` -> Line 5 should be: `from importlib.resources import files`

Fixing that, all the plots in the example_plot notebook come up nicely.

**Comment by kdund** [comment]
pip install for all is, I think, something you need to implement separately (not a bad thing to add an issue for, and grateful for anyone with experience to add this to the pip index)

**Comment by kdund** [comment]
@deisting lmk if the above addition to requirements.txt is sufficient to install.

**Comment by deisting** [comment]
yes! If you have that it runs smoothly.

**Comment by kdund** [comment]
@deisting any chance you could check still? I think it is best for the long-term health of the package that I don't add things without review

**Comment by deisting** [comment]
> @deisting any chance you could check still? I think it is best for the long-term health of the package that I don't add things without review

Had a python3.11 run and it runs swimmingly. (Installing from requirements txt and then running the examples given.)

**Comment by kdund** [comment]
Thanks, @deisting ! Please mark the review as accepted in that case :)

**Review by deisting — APPROVED** [review]
Ah sorry, I did not realise I am this officially a reviewer O:) So yes. Thumbs up! (I have emptied the notebook because of the "git diffs", but you may do not want that.)

**Comment by kdund** [comment]
Thanks, @deisting !

**Pull request merged**
