### PR TITLE
Add limits 2024

### PR DESCRIPTION
**Pull request by kdund**
To add a number of new limits in the standardised format, and remove some duplicates + nonconforming to a misc folder: 

image

### CODE REVIEW

**Comment by yuema137** [comment]
Hi Knut, thanks for the update. This looks good to me. Please see the notebook that I added to check all of the limits, which I believe will be helpful in the future. The only problem is that there is a problem with the `WIMPSI_CRESSTII_2019.csv` file. Could you check a bit with this? Thanks a lot!
image

**Comment by kdund** [comment]
Thanks, @yuema137 for reviewing, and finding a silly bug, scaling also the wimp mass-- should be fixed now

**Comment by yuema137** [comment]
@kdund Thanks for the update! Here is only one minor problem remained:
`Failed for WIMPSI_PandaX4T_2021.csv: could not convert string '\ufeff' to float64 at row 0, column 1.`
There is a comment in the first row that causes this error. Do you mind just removing that row? Or should we separate the clean CSV file from the comments? 
image

**Review by yuema137 — APPROVED** [review]
Looks all good to me now. Thanks!

**Pull request merged**
